image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - install
  - lint
  - build

install_dependencies:
  stage: install
  script:
    - npm install

build:
  stage: build
  script:
    - npm run build
